[package]
name = "stm32h503cb"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-executor = { workspace = true }
hal = { path = "../../hal", features = ["target-stm32h503cb"] }
app = { path = "../../app" }
