[tasks.install-llvm]
install_crate = { rustup_component_name = "llvm-tools", binary = "llvm-objcopy" }
workspace = false

[tasks.install-binutils]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
  "objcopy",
  "--version",
] }
workspace = false
