[toolchain]
channel = "nightly"
profile = "default"
targets = [
  # Cortex-M0,M0+,M1 - STM32 F0,G0, RP2040
  "thumbv6m-none-eabi",
  # Cortex-M4,M7 - STM32 F1,F2,F4,G4
  "thumbv7em-none-eabi",
  # Cortex-M4F,M7F - STM32 F3,F7,H7
  "thumbv7em-none-eabihf",
  # Cortex-M33 - STM32 H5, RP235x (ARM)
  "thumbv8m.main-none-eabihf",
  # CH32, RP235x (RISC-V)
  "riscv32imac-unknown-none-elf",
]
components = ["rust-src", "llvm-tools", "clippy", "rustfmt"]
