[package]
name = "app"
version = "0.1.0"
edition = "2021"

[features]
default = ["blinky", "button"]
blinky = []
blinky-slow = ["blinky"]
button = []

[dependencies]
embassy-executor = { workspace = true }
hal = { path = "../hal", default-features = false }
