[package]
name = "stm32g431cb"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-executor = { workspace = true }
hal = { path = "../../hal", features = ["target-stm32g431cb"] }
app = { path = "../../app" }
