[tasks.firmware-debug]
command = "cargo"
args = [
  "objcopy",
  "--",
  "-O",
  "binary",
  "../../out/thumbv8m.main-none-eabihf/debug/stm32h503.bin",
]

[tasks.dfu-debug]
command = "dfu-util"
args = [
  "-a",
  "0",
  "-s",
  "0x08000000:leave",
  "-D",
  "../../out/thumbv8m.main-none-eabihf/debug/stm32h503.bin",
]
dependencies = ["firmware-debug"]

[tasks.firmware-release]
command = "cargo"
args = [
  "objcopy",
  "--release",
  "--",
  "-O",
  "binary",
  "../../out/thumbv8m.main-none-eabihf/release/stm32h503.bin",
]

[tasks.dfu-release]
command = "dfu-util"
args = [
  "-a",
  "0",
  "-s",
  "0x08000000:leave",
  "-D",
  "../../out/thumbv8m.main-none-eabihf/release/stm32h503.bin",
]
dependencies = ["firmware-release"]
