[build]
target-dir = "out"

[alias]
# TODO: maybe do something here for multi-target/feature stuff

[env]
DEFMT_LOG = "trace"

# [target.thumbv7em-none-eabihf]
# TODO: can this be changed from build.rs or some cargo runner?
# runner = 'probe-rs run --chip STM32H743VITx'
